var exports = module.exports = {};

exports.testGetPageRange_reply = { server: 'GitHub.com',
date: 'Mon, 25 Nov 2019 10:01:07 GMT',
'content-type': 'application/json; charset=utf-8',
'content-length': '148780',
connection: 'close',
status: '200 OK',
'x-ratelimit-limit': '30',
'x-ratelimit-remaining': '25',
'x-ratelimit-reset': '1574676117',
'cache-control': 'no-cache',
'x-oauth-scopes': 'notifications, repo',
'x-accepted-oauth-scopes': '',
'x-github-media-type': 'github.v3',
link: '<https://api.github.com/search/repositories?q=cs225+in%3Aname%2Cdescription&page=2>; rel="next", <https://api.github.com/search/repositories?q=cs225+in%3Aname%2Cdescription&page=16>; rel="last"',
'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
'access-control-allow-origin': '*',
'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
'x-frame-options': 'deny',
'x-content-type-options': 'nosniff',
'x-xss-protection': '1; mode=block',
'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
'content-security-policy': 'default-src \'none\'',
'x-github-request-id': '5542:2330:5FCAA7:E722C6:5DDBA662'}